services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - 5432:5432
    networks:
      - postgres-net
networks:
  postgres-net:
    name: postgres-net
