INSERT INTO UNIDADE (ID, CREATED_AT, UPDATED_AT, NAME)
    VALUES (nextval('SEQ_UNIDADE'),NOW(), NOW(), 'UNIDADE');

INSERT INTO UNIDADE (ID, CREATED_AT, UPDATED_AT, NAME)
VALUES (nextval('SEQ_UNIDADE'),NOW(), NOW(), 'UNIDADE');